on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: sam validate

      - run: sam build --use-container

      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name uplus-assignment --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }}